# Generated by Django 5.0 on 2023-12-23 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="members",
            new_name="users",
        ),
    ]
