# Generated by Django 5.0 on 2023-12-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
