# Generated by Django 5.0 on 2023-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convos", "0002_alter_convo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
